extended functionalities of Report and TrainingProgram
mpieron/JavaBasicForQAFinalTask pull request #1
Opened 2021-12-22 07:17 UTC by mpieron

2021-12-22 09:17 UTC, ghostdance386 requested changes
Once You'll make the changes, I think You should start writing tests for all these methods. And from now on, when You'll be adding some new logic, make sure that You covered it with tests to see if it's working.

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Course.java
> -    public void finishedCourse(){
change method name to more descriptive, for example setCourseToFinished or setFinish or just finishCourse

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Course.java
>          return  courseName + "\t\t" + durationHours;
please use String.format or Stringbuilder to concatenate Strings

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Course.java
>  public class Course {
remember to create setter methods for other fields or create a constructor with required arguments

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +    private final LocalDateTime now = LocalDateTime.now();
reportGenerationTime would be more descriptive name for this :)

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +            report = (input == '0' || input == ' ')  ? generateShortReport(student, trainingProgram) : generateFullReport(student, trainingProgram);
you make this check for every iteration of the loop. We need to check it only once

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +    public String generateReport(char input){
remember to add validation of the input: if it's not one of expected values, exception should be thrown

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +        for (Map.Entry<Student, TrainingProgram> entry : studentCourses.entrySet()) {
later on I'd like this to be done with streams - as a bonus task ;)

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +        report += finished ? "are left until the end." : "have passed since the end.";
please use String.format or StringBuilder for String concatenation

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Report.java
> +        report += training.isFinished(now) ? "are left until the end." : "have passed since the end.";
please use String.format or StringBuilder for String concatenation

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Student.java
>          id ++;
you can increment the id in the same line where you assign it to studentId

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Student.java
> +        return  name + " " + surname;
please use String.format or StringBuilder for String concatenation

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/Training.java
> +public interface Training {
interfaces are used more for defining the common behavior of implementing classes. in this case an abstract class would be more suitable

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +                startDate.plusDays(days).getDayOfYear(), 10+hours, 0);
LocalDateTime.of method needs day-of-month here instead of day-of-year

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +        return LocalDateTime.of(startDate.getYear(), startDate.getMonthValue(),
can we be sure that the end date will always be in the same year and month and start date? what if we start course on 30.12?

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +                "End date: " + calculateEndDate() + "\n";
String.format or Stringbuilder please

2021-12-22 09:17 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +public class TrainingProgram  implements Training {
this is the only class that implements this interface - maybe we don't need the interface at this moment?

2021-12-23 08:47 UTC, ghostdance386 requested changes

2021-12-23 08:47 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +        }
this is nice, but it's easier to read such expressions when the negative condition is in else block. Please switch conditions places just for readability's sake

2021-12-23 08:47 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +            days += 1;
days++

2021-12-23 08:47 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +                    days -= 1;
days--

2021-12-23 08:47 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +        return durationTime;
this is quite easy to do with stream. please rework

2021-12-23 08:47 UTC, ghostdance386 commented on src/main/java/Models/TrainingProgram.java
> +    private static final int workingDays = 5;
if it's not used, delete it please

2021-12-23 08:47 UTC, ghostdance386 commented on src/test/java/Models/TrainingProgramTest.java
> +    TrainingProgram program;
these can be private

2021-12-23 08:47 UTC, ghostdance386 commented on src/test/java/Models/TrainingProgramTest.java
> +public class TrainingProgramTest {
please add more testcases with calculations. you can make them parameterized tests to avoid duplication

2022-01-03 09:13 UTC, kdyla-griddynamics requested changes
looking good :) maybe try to 'break' something in tests - negative test cases are important part of test suite

2022-01-03 09:13 UTC, kdyla-griddynamics commented on src/main/java/Models/Report.java
> +        else {
you only check if input is 0/empty and then else. what if the input would be 2, k, $%? we need more strict validation here

2022-01-03 09:13 UTC, kdyla-griddynamics commented on src/main/java/Models/TrainingProgram.java
> +        return (days > 0 ? String.format("%d d ", days) : "") + (hours > 0 ? String.format("%d hours", hours) : "");
please print "days" instead of "d"

2022-01-03 09:13 UTC, kdyla-griddynamics commented on src/main/java/Models/TrainingProgram.java
> +            if(before.plusDays(1).getDayOfWeek() != DayOfWeek.SATURDAY && before.plusDays(1).getDayOfWeek() != DayOfWeek.SUNDAY){
please try to make the condition positive instead of (!=) negative. it will be easier to read

2022-01-03 09:13 UTC, kdyla-griddynamics commented on src/main/java/Models/TrainingProgram.java
> +            if(endDate.plusDays(1).getDayOfWeek() != DayOfWeek.SUNDAY && endDate.plusDays(1).getDayOfWeek() != DayOfWeek.SATURDAY) {
please try to make the condition positive instead of (!=) negative. it will be easier to read

2022-01-03 09:13 UTC, kdyla-griddynamics commented on src/main/java/Models/TrainingSystem.java
> +        Report report = new Report(studentCourses, LocalDateTime.of(2021,12,3,15,0));
according to readme, I think report generation time should be the current time

2022-01-04 08:38 UTC, kdyla-griddynamics approved these changes

2022-01-04 08:38 UTC, kdyla-griddynamics commented on src/main/java/Models/TrainingSystem.java
> +            System.exit(1);
instead of manually exiting the program, please put code from lines 34-40 inside the try block

2022-01-04 09:34 UTC, kdyla-griddynamics commented on src/main/java/Models/Report.java
> +    private String trainingStatusSupport(TrainingProgram training){
one thing that I found just now. this method counts the time to or after completion, but in working hours. It should count in full 24 hour manner

2022-01-04 10:05 UTC, merged